### PR TITLE
Feature test backend performance

### PR DESCRIPTION
**Pull request by kome12**
## Description

Add stopwatch logs for key create / get calls to see how long it takes on the staging server versus the local server.
So far I put it on the below API calls
- Create Garden
- Create bulk rules
- Get Garden by Garden Id (fully populated)

## Closes issue(s)

#69 

## Screenshots

スクリーンショット 2021-09-02 21 16 58

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

## Checklist

- [X] I have tested this code

### CODE REVIEW

**Comment by kome12** [comment]
@daiHash @yukari-n-erb Sorry, I branched off of the open PR branch so please merge this after #66 is okay!

**Comment by kome12** [comment]
And can we push this to staging to we can compare the times locally versus staging? It's not too bad when I'm running both frontend and backend locally so it might not be the MongoDB but the Heroku server.
スクリーンショット 2021-09-02 21 22 36
スクリーンショット 2021-09-02 21 16 58

**Review by daiHash — APPROVED** [review]
Thanks
Let test the heroku servers, probably what we know but I think is good to test and be sure about the issue

**Comment by kome12** [comment]
@daiHash @yukari-n-erb Looked at the numbers for staging but it is almost 3 times slower than my local. The worst time for GetGarden fully populated is around 2 seconds, while the staging is a little under 6 seconds. There clearly is a difference in performance.

スクリーンショット 2021-09-03 15 09 36
スクリーンショット 2021-09-03 15 07 18

**Pull request merged**
